# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/notionstools',
                'doc_host': 'https://tjpalanca.com',
                'git_url': 'https://github.com/tjpalanca/notionstools.git',
                'lib_path': 'notiontools'},
  'syms': {}}
